version: '3'

services:
  backend:
    command: sh -c "npm install && npm run start:dev"
  frontend:
    image: node:21-alpine
    container_name: react-app
    working_dir: /app
    ports: 
      - 3001:3000
    volumes:
      - ./fe-react/:/app
    command: sh -c "npm install && npm run start"
  proxy:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./proxy.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend