version: '3'

services:
  backend:
    image: node:21-alpine
    container_name: nest-app
    working_dir: /app
    ports: 
      - 3000:3000
    volumes:
      - ./be-nest/:/app
    command: sh -c "npm install && npm start"
  proxy:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - backend